---

- name: installing packages for python env
  become: yes
  apt:
    name: 
      - python3
      - python3-pip
    update_cache: yes

- name: Create directory
  file:
    path: /home/ubuntu/ansible
    state: directory
  
- name: install apache2
  become: yes
  apt:
    name: apache2
    state: present
    update_cache: yes