---

- name: Git present
  hosts: all
  become: true

  tasks: 
    - name: Check git on "RedHat"
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"
    - name: Check git on "Debian"
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"