---

- name: Install appache2 on all nodes
  hosts: all
  become: true

  tasks: 
    - name: Install apache2 package
      apt:
        name: apache2
        state: present
    - name: Start apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copy index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html