---
# tasks file for InstallDockerOnEc2
# sudo yum update -y
# sudo amazon-linux-extras -y install docker
# sudo service docker start
# sudo systemctl start docker
# sudo service docker status
# sudo groupadd docker
# sudo usermod -a -G docker ec2-user
# newgrp docker
# docker — version
# docker version

- name: update
  ansible.builtin.yum:
    name: "*"
    state: latest
- name: Install docker
  ansible.builtin.shell: amazon-linux-extras -y install docker
- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
- name: Check docker
  ansible.builtin.systemd:
    name: docker
    state: started
- name: check status of docker
  ansible.builtin.shell: systemctl status docker
- name: Add docker group
  ansible.builtin.shell: groupadd docker
- name: Add user to docker group
  ansible.builtin.shell: usermod -a -G docker ec2-user
- name: Newgrp docker
  ansible.builtin.shell: newgrp docker
- name: Check docker version
  ansible.builtin.shell: docker --version
- name: Check docker version
  ansible.builtin.shell: docker version
