
---

# version: '3.8'

services:
  control-node:
    image: ansible 
    container_name: control-node
    volumes:
      - /Users/mreddy/Developer/Mallikarjun/GitRepository/Ansible/:/workingdir
    networks:
      - ansible-net
  node1:
    image: managednode
    container_name: node1
    networks:
      - ansible-net
  node2:
    image: managednode
    container_name: node2
    networks:
      - ansible-net
  node3:
    image: managednode
    container_name: node3
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge