# Use the official Ubuntu base image
FROM ubuntu:latest

# Update the package list and install necessary packages
RUN apt-get update -y && \
    apt-get install -y openssh-server sudo python3 python3-pip libpam-systemd && \
    apt-get clean

# Create a user for Ansible to connect
ARG USER=ansibleuser
ARG PASS="ansibleuser"
RUN useradd -m -s /bin/bash $USER && echo "$USER:$PASS" | chpasswd

# Give the user sudo privileges without a password
RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN echo ${USER}

RUN echo ${PASS}

RUN mkdir -p /home/${USER}/.ssh && \
    chmod 700 /home/${USER}/.ssh && \
    chown ${USER}:${PASS} /home/${USER}/.ssh

COPY authorized_keys /home/${USER}/.ssh/authorized_keys

# Configure SSH to allow password authentication
RUN mkdir /var/run/sshd && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

# USER &{USER}    
RUN export ENV=Development && \
    echo "export ENV=Development" >> /home/${USER}/.bashrc
# Expose the SSH port
EXPOSE 22

# Start the SSH service
CMD ["/usr/sbin/sshd", "-D"]