FROM ubuntu:latest

RUN apt-get update 
RUN apt-get install -y nano
RUN apt-get install -y openssh-server
RUN apt-get install -y python3
RUN apt-get install -y ansible

RUN ansible --version
# RUN ansible-config init --disable >ansible.cfg

COPY  . /ansible

# RUN ssh-keygen

# RUN service ssh status 

# RUN service ssh start